version: "3"

services:
  vote:
    build: ./vote_app
    command: python app.py
    volumes:
      - ./vote_app:/app
    ports:
      - "5000:80"   # Exposing the service to outside world.


  db:
    image: mysql
    container_name: mysql_test_v1
    restart: always
    volumes:
      - "/home/vineetkumar_patil123/custom_storage_docker_volume/mysql_db_v1/:/var/lib/mysql"
      - "/home/vineetkumar_patil123/custom_docker_volume/vote.sql:/vote.sql"
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: student_db
    ports:
      - "3307:3306"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: