version: "3"

services:
  flask:
    image: vote_app:latest  # creates image by this name.
    container_name: vote_app_container
    restart: always
    build:
      context: ./vote_app
      dockerfile: Dockerfile  # can be Dockerfile-dev , Dockerfile-prod
    volumes:
      - ./vote_app:/app
    ports:
      - "20001:20001"   # Exposing the service to outside world.
    networks:
      - app-tier

  mysql_db: 
    image: mysql
    container_name: mysql_db
    restart: always
    volumes:
      - "/home/vineetkumar_patil123/custom_storage_docker_volume/mysql_db_v1/:/var/lib/mysql"
      - "/home/vineetkumar_patil123/custom_docker_volume/vote.sql:/vote.sql"
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: vote_db
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
    ports:
      - "3306:3306"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
  front-tier:
  back-tier: